### ISSUE TITLE
first stable release?

### ISSUE THREAD

**Issue by jangorecki** [olafmersmann/microbenchmarkCore#1]
Any bigger tasks on roadmap for the first stable release?
If package would be quite stable then it would be great to have it published on [drat](https://github.com/eddelbuettel/drat) or CRAN.
If you are not aware of drat, it allows users to install from base R by:

``` r
install.packages("microbenchmarkCore", repos="https://olafmersmann.github.io/drat")
```

And works the same way as CRAN mirrors in terms of `update.packages()` etc.

**Comment by olafmersmann** [comment]
Didn't know about `drat`. Sounds like a great idea. 

The following should work now:

``` splus
install.packages("microbenchmarkCore", repos="http://olafmersmann.github.io/drat")
```

**Comment by jangorecki** [comment]
@olafmersmann drat requires to setup repo. Easiest way is to fork drat branch, use `drat::insertPackage("microbenchmarkCore_1.0.0.tar.gz", "path/drat")`, then commit and push to `gh-pages` branch. More info on [DratForPackageAuthors](http://eddelbuettel.github.io/drat/DratForPackageAuthors.html)

**Comment by jangorecki** [comment]
@olafmersmann didn't spot you where so fast with setting drat. great!
