### ISSUE TITLE
Avoid scientific notation in print.microbenchmark

### ISSUE THREAD

**Issue by jangorecki** [olafmersmann/microbenchmarkCore#3]
Taking following case - instantly executed expression:

``` r
library(microbenchmarkCore)
system.nanotime(1)
#     user   system  elapsed 
#       NA       NA 2.47e-07 
format(system.nanotime(1), scientific = FALSE)
#     user.self      sys.self       elapsed    user.child     sys.child 
# "         NA" "         NA" "0.000000363" "         NA" "         NA"
print(microbenchmark(1), unit="s") # scientific doesn't change anything
# Unit: seconds
#  expr   min    lq     mean median    uq      max neval
#     1 6e-09 6e-09 1.24e-08  7e-09 7e-09 5.77e-07   100
```

I see current implemention is printed based on data.frame, and simple `scientific` arg will not work.
Do you think it is better to print using other method, e.g. matrix or try to format data.frame before printing?

**Comment by olafmersmann** [comment]
I'm not sure if I mind the scentific notation.

In your third example (`print(microbenchmark(...` you force the use of scientific notation by specifying a badly chosen unit. `print.microbenchmark` tries hard to avoid SI notation by choosing a unit for you but if you force the unit, better print in SI than have overly long lines.

Thoughts?

**Comment by jangorecki** [comment]
Yeah, maybe it is better to visually compare without fixed `units` just using

``` r
print(microbenchmark(1))
# Unit: nanoseconds
#  expr min lq  mean median uq max neval
#     1   5  6 15.06      7  7 853   100
```
